apiVersion: v1
stringData:
  token: "token-to-authenticate-to-frp-server"
kind: Secret
metadata:
  name: client-01-secret
  namespace: default
type: Opaque
---
apiVersion: v1
stringData:
  key: "token-to-authenticate-between-upstream-and-visitor"
kind: Secret
metadata:
  name: nginx-xtcp-secret
  namespace: default
type: Opaque
