apiVersion: v1
kind: Service
metadata:
  name: web-auto
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerClass: frp.zufardhiyaulhaq.com/frp
  selector:
    app: web
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
