---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ template "frp-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-controller-manager
spec:
  replicas: {{ .Values.operator.replica }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --health-probe-bind-address=:8081
        {{- if .Values.metrics.secure }}
        - --metrics-bind-address=:8443
        - --metrics-secure=true
        {{- else }}
        - --metrics-bind-address=:8080
        - --metrics-secure=false
        {{- end }}
        - --leader-elect
        - --enable-loadbalancer-controller={{ .Values.loadBalancer.enabled }}
        command:
        - /manager
        image: "{{ .Values.operator.image }}:{{ .Values.operator.tag }}"
        imagePullPolicy: {{ .Values.operator.imagePullPolicy | default "Always" }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        {{- if .Values.metrics.secure }}
        - containerPort: 8443
          name: https
          protocol: TCP
        {{- else }}
        - containerPort: 8080
          name: http
          protocol: TCP
        {{- end }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{ .Values.resources | toYaml  | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ .Release.Name }}-controller-manager
      terminationGracePeriodSeconds: 10
