//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Client) DeepCopyInto(out *Client) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Client.
func (in *Client) DeepCopy() *Client {
	if in == nil {
		return nil
	}
	out := new(Client)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Client) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientList) DeepCopyInto(out *ClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Client, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientList.
func (in *ClientList) DeepCopy() *ClientList {
	if in == nil {
		return nil
	}
	out := new(ClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec) DeepCopyInto(out *ClientSpec) {
	*out = *in
	in.Server.DeepCopyInto(&out.Server)
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(ClientSpec_PodTemplate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec.
func (in *ClientSpec) DeepCopy() *ClientSpec {
	if in == nil {
		return nil
	}
	out := new(ClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec_PodTemplate) DeepCopyInto(out *ClientSpec_PodTemplate) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec_PodTemplate.
func (in *ClientSpec_PodTemplate) DeepCopy() *ClientSpec_PodTemplate {
	if in == nil {
		return nil
	}
	out := new(ClientSpec_PodTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec_Server) DeepCopyInto(out *ClientSpec_Server) {
	*out = *in
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	in.Authentication.DeepCopyInto(&out.Authentication)
	if in.AdminServer != nil {
		in, out := &in.AdminServer, &out.AdminServer
		*out = new(ClientSpec_Server_AdminServer)
		(*in).DeepCopyInto(*out)
	}
	if in.STUNServer != nil {
		in, out := &in.STUNServer, &out.STUNServer
		*out = new(string)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(ClientSpec_Server_TLS)
		(*in).DeepCopyInto(*out)
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(ClientSpec_Server_Transport)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec_Server.
func (in *ClientSpec_Server) DeepCopy() *ClientSpec_Server {
	if in == nil {
		return nil
	}
	out := new(ClientSpec_Server)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec_Server_AdminServer) DeepCopyInto(out *ClientSpec_Server_AdminServer) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(ClientSpec_Server_AdminServer_Username)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(ClientSpec_Server_AdminServer_Password)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec_Server_AdminServer.
func (in *ClientSpec_Server_AdminServer) DeepCopy() *ClientSpec_Server_AdminServer {
	if in == nil {
		return nil
	}
	out := new(ClientSpec_Server_AdminServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec_Server_AdminServer_Password) DeepCopyInto(out *ClientSpec_Server_AdminServer_Password) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec_Server_AdminServer_Password.
func (in *ClientSpec_Server_AdminServer_Password) DeepCopy() *ClientSpec_Server_AdminServer_Password {
	if in == nil {
		return nil
	}
	out := new(ClientSpec_Server_AdminServer_Password)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec_Server_AdminServer_Username) DeepCopyInto(out *ClientSpec_Server_AdminServer_Username) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec_Server_AdminServer_Username.
func (in *ClientSpec_Server_AdminServer_Username) DeepCopy() *ClientSpec_Server_AdminServer_Username {
	if in == nil {
		return nil
	}
	out := new(ClientSpec_Server_AdminServer_Username)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec_Server_Authentication) DeepCopyInto(out *ClientSpec_Server_Authentication) {
	*out = *in
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(ClientSpec_Server_Authentication_Token)
		**out = **in
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(ClientSpec_Server_Authentication_OIDC)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec_Server_Authentication.
func (in *ClientSpec_Server_Authentication) DeepCopy() *ClientSpec_Server_Authentication {
	if in == nil {
		return nil
	}
	out := new(ClientSpec_Server_Authentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec_Server_Authentication_OIDC) DeepCopyInto(out *ClientSpec_Server_Authentication_OIDC) {
	*out = *in
	out.ClientID = in.ClientID
	out.ClientSecret = in.ClientSecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec_Server_Authentication_OIDC.
func (in *ClientSpec_Server_Authentication_OIDC) DeepCopy() *ClientSpec_Server_Authentication_OIDC {
	if in == nil {
		return nil
	}
	out := new(ClientSpec_Server_Authentication_OIDC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec_Server_Authentication_Token) DeepCopyInto(out *ClientSpec_Server_Authentication_Token) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec_Server_Authentication_Token.
func (in *ClientSpec_Server_Authentication_Token) DeepCopy() *ClientSpec_Server_Authentication_Token {
	if in == nil {
		return nil
	}
	out := new(ClientSpec_Server_Authentication_Token)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec_Server_TLS) DeepCopyInto(out *ClientSpec_Server_TLS) {
	*out = *in
	if in.CertFile != nil {
		in, out := &in.CertFile, &out.CertFile
		*out = new(SecretRef)
		**out = **in
	}
	if in.KeyFile != nil {
		in, out := &in.KeyFile, &out.KeyFile
		*out = new(SecretRef)
		**out = **in
	}
	if in.TrustedCAFile != nil {
		in, out := &in.TrustedCAFile, &out.TrustedCAFile
		*out = new(ConfigMapOrSecretRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec_Server_TLS.
func (in *ClientSpec_Server_TLS) DeepCopy() *ClientSpec_Server_TLS {
	if in == nil {
		return nil
	}
	out := new(ClientSpec_Server_TLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec_Server_Transport) DeepCopyInto(out *ClientSpec_Server_Transport) {
	*out = *in
	if in.TCPMux != nil {
		in, out := &in.TCPMux, &out.TCPMux
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec_Server_Transport.
func (in *ClientSpec_Server_Transport) DeepCopy() *ClientSpec_Server_Transport {
	if in == nil {
		return nil
	}
	out := new(ClientSpec_Server_Transport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientStatus) DeepCopyInto(out *ClientStatus) {
	*out = *in
	if in.LastReconnect != nil {
		in, out := &in.LastReconnect, &out.LastReconnect
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientStatus.
func (in *ClientStatus) DeepCopy() *ClientStatus {
	if in == nil {
		return nil
	}
	out := new(ClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapOrSecretRef) DeepCopyInto(out *ConfigMapOrSecretRef) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(Secret)
		**out = **in
	}
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(ConfigMapRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapOrSecretRef.
func (in *ConfigMapOrSecretRef) DeepCopy() *ConfigMapOrSecretRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapOrSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapRef) DeepCopyInto(out *ConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapRef.
func (in *ConfigMapRef) DeepCopy() *ConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPHeaders) DeepCopyInto(out *HTTPHeaders) {
	*out = *in
	if in.Set != nil {
		in, out := &in.Set, &out.Set
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPHeaders.
func (in *HTTPHeaders) DeepCopy() *HTTPHeaders {
	if in == nil {
		return nil
	}
	out := new(HTTPHeaders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancer) DeepCopyInto(out *LoadBalancer) {
	*out = *in
	if in.GroupKey != nil {
		in, out := &in.GroupKey, &out.GroupKey
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancer.
func (in *LoadBalancer) DeepCopy() *LoadBalancer {
	if in == nil {
		return nil
	}
	out := new(LoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Secret) DeepCopyInto(out *Secret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Secret.
func (in *Secret) DeepCopy() *Secret {
	if in == nil {
		return nil
	}
	out := new(Secret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Upstream) DeepCopyInto(out *Upstream) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Upstream.
func (in *Upstream) DeepCopy() *Upstream {
	if in == nil {
		return nil
	}
	out := new(Upstream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Upstream) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamList) DeepCopyInto(out *UpstreamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Upstream, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamList.
func (in *UpstreamList) DeepCopy() *UpstreamList {
	if in == nil {
		return nil
	}
	out := new(UpstreamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpstreamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamPlugin) DeepCopyInto(out *UpstreamPlugin) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(SecretRef)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(SecretRef)
		**out = **in
	}
	if in.HTTPUser != nil {
		in, out := &in.HTTPUser, &out.HTTPUser
		*out = new(SecretRef)
		**out = **in
	}
	if in.HTTPPassword != nil {
		in, out := &in.HTTPPassword, &out.HTTPPassword
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamPlugin.
func (in *UpstreamPlugin) DeepCopy() *UpstreamPlugin {
	if in == nil {
		return nil
	}
	out := new(UpstreamPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec) DeepCopyInto(out *UpstreamSpec) {
	*out = *in
	if in.TCP != nil {
		in, out := &in.TCP, &out.TCP
		*out = new(UpstreamSpec_TCP)
		(*in).DeepCopyInto(*out)
	}
	if in.UDP != nil {
		in, out := &in.UDP, &out.UDP
		*out = new(UpstreamSpec_UDP)
		**out = **in
	}
	if in.STCP != nil {
		in, out := &in.STCP, &out.STCP
		*out = new(UpstreamSpec_STCP)
		(*in).DeepCopyInto(*out)
	}
	if in.XTCP != nil {
		in, out := &in.XTCP, &out.XTCP
		*out = new(UpstreamSpec_XTCP)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(UpstreamSpec_HTTP)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPS != nil {
		in, out := &in.HTTPS, &out.HTTPS
		*out = new(UpstreamSpec_HTTPS)
		(*in).DeepCopyInto(*out)
	}
	if in.TCPMUX != nil {
		in, out := &in.TCPMUX, &out.TCPMUX
		*out = new(UpstreamSpec_TCPMUX)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec.
func (in *UpstreamSpec) DeepCopy() *UpstreamSpec {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_HTTP) DeepCopyInto(out *UpstreamSpec_HTTP) {
	*out = *in
	if in.CustomDomains != nil {
		in, out := &in.CustomDomains, &out.CustomDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequestHeaders != nil {
		in, out := &in.RequestHeaders, &out.RequestHeaders
		*out = new(HTTPHeaders)
		(*in).DeepCopyInto(*out)
	}
	if in.ResponseHeaders != nil {
		in, out := &in.ResponseHeaders, &out.ResponseHeaders
		*out = new(HTTPHeaders)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPUser != nil {
		in, out := &in.HTTPUser, &out.HTTPUser
		*out = new(SecretRef)
		**out = **in
	}
	if in.HTTPPassword != nil {
		in, out := &in.HTTPPassword, &out.HTTPPassword
		*out = new(SecretRef)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(UpstreamSpec_HTTP_HealthCheck)
		**out = **in
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(UpstreamSpec_TCP_Transport)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_HTTP.
func (in *UpstreamSpec_HTTP) DeepCopy() *UpstreamSpec_HTTP {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_HTTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_HTTPS) DeepCopyInto(out *UpstreamSpec_HTTPS) {
	*out = *in
	if in.CustomDomains != nil {
		in, out := &in.CustomDomains, &out.CustomDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProxyProtocol != nil {
		in, out := &in.ProxyProtocol, &out.ProxyProtocol
		*out = new(string)
		**out = **in
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(UpstreamSpec_TCP_Transport)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_HTTPS.
func (in *UpstreamSpec_HTTPS) DeepCopy() *UpstreamSpec_HTTPS {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_HTTPS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_HTTP_HealthCheck) DeepCopyInto(out *UpstreamSpec_HTTP_HealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_HTTP_HealthCheck.
func (in *UpstreamSpec_HTTP_HealthCheck) DeepCopy() *UpstreamSpec_HTTP_HealthCheck {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_HTTP_HealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_STCP) DeepCopyInto(out *UpstreamSpec_STCP) {
	*out = *in
	out.SecretKey = in.SecretKey
	if in.ProxyProtocol != nil {
		in, out := &in.ProxyProtocol, &out.ProxyProtocol
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(UpstreamSpec_TCP_HealthCheck)
		**out = **in
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(UpstreamSpec_TCP_Transport)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowUsers != nil {
		in, out := &in.AllowUsers, &out.AllowUsers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_STCP.
func (in *UpstreamSpec_STCP) DeepCopy() *UpstreamSpec_STCP {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_STCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_STCP_SecretKey) DeepCopyInto(out *UpstreamSpec_STCP_SecretKey) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_STCP_SecretKey.
func (in *UpstreamSpec_STCP_SecretKey) DeepCopy() *UpstreamSpec_STCP_SecretKey {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_STCP_SecretKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_TCP) DeepCopyInto(out *UpstreamSpec_TCP) {
	*out = *in
	out.Server = in.Server
	if in.ProxyProtocol != nil {
		in, out := &in.ProxyProtocol, &out.ProxyProtocol
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(UpstreamSpec_TCP_HealthCheck)
		**out = **in
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(UpstreamSpec_TCP_Transport)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancer != nil {
		in, out := &in.LoadBalancer, &out.LoadBalancer
		*out = new(LoadBalancer)
		(*in).DeepCopyInto(*out)
	}
	if in.Plugin != nil {
		in, out := &in.Plugin, &out.Plugin
		*out = new(UpstreamPlugin)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_TCP.
func (in *UpstreamSpec_TCP) DeepCopy() *UpstreamSpec_TCP {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_TCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_TCPMUX) DeepCopyInto(out *UpstreamSpec_TCPMUX) {
	*out = *in
	if in.CustomDomains != nil {
		in, out := &in.CustomDomains, &out.CustomDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(UpstreamSpec_TCP_Transport)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_TCPMUX.
func (in *UpstreamSpec_TCPMUX) DeepCopy() *UpstreamSpec_TCPMUX {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_TCPMUX)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_TCP_HealthCheck) DeepCopyInto(out *UpstreamSpec_TCP_HealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_TCP_HealthCheck.
func (in *UpstreamSpec_TCP_HealthCheck) DeepCopy() *UpstreamSpec_TCP_HealthCheck {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_TCP_HealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_TCP_Server) DeepCopyInto(out *UpstreamSpec_TCP_Server) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_TCP_Server.
func (in *UpstreamSpec_TCP_Server) DeepCopy() *UpstreamSpec_TCP_Server {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_TCP_Server)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_TCP_Transport) DeepCopyInto(out *UpstreamSpec_TCP_Transport) {
	*out = *in
	if in.BandwdithLimit != nil {
		in, out := &in.BandwdithLimit, &out.BandwdithLimit
		*out = new(UpstreamSpec_TCP_Transport_BandwdithLimit)
		**out = **in
	}
	if in.ProxyURL != nil {
		in, out := &in.ProxyURL, &out.ProxyURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_TCP_Transport.
func (in *UpstreamSpec_TCP_Transport) DeepCopy() *UpstreamSpec_TCP_Transport {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_TCP_Transport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_TCP_Transport_BandwdithLimit) DeepCopyInto(out *UpstreamSpec_TCP_Transport_BandwdithLimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_TCP_Transport_BandwdithLimit.
func (in *UpstreamSpec_TCP_Transport_BandwdithLimit) DeepCopy() *UpstreamSpec_TCP_Transport_BandwdithLimit {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_TCP_Transport_BandwdithLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_UDP) DeepCopyInto(out *UpstreamSpec_UDP) {
	*out = *in
	out.Server = in.Server
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_UDP.
func (in *UpstreamSpec_UDP) DeepCopy() *UpstreamSpec_UDP {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_UDP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_UDP_Server) DeepCopyInto(out *UpstreamSpec_UDP_Server) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_UDP_Server.
func (in *UpstreamSpec_UDP_Server) DeepCopy() *UpstreamSpec_UDP_Server {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_UDP_Server)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_XTCP) DeepCopyInto(out *UpstreamSpec_XTCP) {
	*out = *in
	out.SecretKey = in.SecretKey
	if in.ProxyProtocol != nil {
		in, out := &in.ProxyProtocol, &out.ProxyProtocol
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(UpstreamSpec_TCP_HealthCheck)
		**out = **in
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(UpstreamSpec_TCP_Transport)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowUsers != nil {
		in, out := &in.AllowUsers, &out.AllowUsers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_XTCP.
func (in *UpstreamSpec_XTCP) DeepCopy() *UpstreamSpec_XTCP {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_XTCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_XTCP_SecretKey) DeepCopyInto(out *UpstreamSpec_XTCP_SecretKey) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_XTCP_SecretKey.
func (in *UpstreamSpec_XTCP_SecretKey) DeepCopy() *UpstreamSpec_XTCP_SecretKey {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_XTCP_SecretKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamStatus) DeepCopyInto(out *UpstreamStatus) {
	*out = *in
	if in.RegisteredAt != nil {
		in, out := &in.RegisteredAt, &out.RegisteredAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamStatus.
func (in *UpstreamStatus) DeepCopy() *UpstreamStatus {
	if in == nil {
		return nil
	}
	out := new(UpstreamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Visitor) DeepCopyInto(out *Visitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Visitor.
func (in *Visitor) DeepCopy() *Visitor {
	if in == nil {
		return nil
	}
	out := new(Visitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Visitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisitorList) DeepCopyInto(out *VisitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Visitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisitorList.
func (in *VisitorList) DeepCopy() *VisitorList {
	if in == nil {
		return nil
	}
	out := new(VisitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VisitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisitorSpec) DeepCopyInto(out *VisitorSpec) {
	*out = *in
	if in.STCP != nil {
		in, out := &in.STCP, &out.STCP
		*out = new(VisitorSpec_STCP)
		**out = **in
	}
	if in.XTCP != nil {
		in, out := &in.XTCP, &out.XTCP
		*out = new(VisitorSpec_XTCP)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisitorSpec.
func (in *VisitorSpec) DeepCopy() *VisitorSpec {
	if in == nil {
		return nil
	}
	out := new(VisitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisitorSpec_Fallback) DeepCopyInto(out *VisitorSpec_Fallback) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisitorSpec_Fallback.
func (in *VisitorSpec_Fallback) DeepCopy() *VisitorSpec_Fallback {
	if in == nil {
		return nil
	}
	out := new(VisitorSpec_Fallback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisitorSpec_STCP) DeepCopyInto(out *VisitorSpec_STCP) {
	*out = *in
	out.ServerSecretKey = in.ServerSecretKey
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisitorSpec_STCP.
func (in *VisitorSpec_STCP) DeepCopy() *VisitorSpec_STCP {
	if in == nil {
		return nil
	}
	out := new(VisitorSpec_STCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisitorSpec_STCP_ServerSecretKey) DeepCopyInto(out *VisitorSpec_STCP_ServerSecretKey) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisitorSpec_STCP_ServerSecretKey.
func (in *VisitorSpec_STCP_ServerSecretKey) DeepCopy() *VisitorSpec_STCP_ServerSecretKey {
	if in == nil {
		return nil
	}
	out := new(VisitorSpec_STCP_ServerSecretKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisitorSpec_XTCP) DeepCopyInto(out *VisitorSpec_XTCP) {
	*out = *in
	out.ServerSecretKey = in.ServerSecretKey
	if in.Fallback != nil {
		in, out := &in.Fallback, &out.Fallback
		*out = new(VisitorSpec_Fallback)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisitorSpec_XTCP.
func (in *VisitorSpec_XTCP) DeepCopy() *VisitorSpec_XTCP {
	if in == nil {
		return nil
	}
	out := new(VisitorSpec_XTCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisitorSpec_XTCP_ServerSecretKey) DeepCopyInto(out *VisitorSpec_XTCP_ServerSecretKey) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisitorSpec_XTCP_ServerSecretKey.
func (in *VisitorSpec_XTCP_ServerSecretKey) DeepCopy() *VisitorSpec_XTCP_ServerSecretKey {
	if in == nil {
		return nil
	}
	out := new(VisitorSpec_XTCP_ServerSecretKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisitorStatus) DeepCopyInto(out *VisitorStatus) {
	*out = *in
	if in.ConnectedAt != nil {
		in, out := &in.ConnectedAt, &out.ConnectedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisitorStatus.
func (in *VisitorStatus) DeepCopy() *VisitorStatus {
	if in == nil {
		return nil
	}
	out := new(VisitorStatus)
	in.DeepCopyInto(out)
	return out
}
