//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Client) DeepCopyInto(out *Client) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Client.
func (in *Client) DeepCopy() *Client {
	if in == nil {
		return nil
	}
	out := new(Client)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Client) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientList) DeepCopyInto(out *ClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Client, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientList.
func (in *ClientList) DeepCopy() *ClientList {
	if in == nil {
		return nil
	}
	out := new(ClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec) DeepCopyInto(out *ClientSpec) {
	*out = *in
	in.Server.DeepCopyInto(&out.Server)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec.
func (in *ClientSpec) DeepCopy() *ClientSpec {
	if in == nil {
		return nil
	}
	out := new(ClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec_Server) DeepCopyInto(out *ClientSpec_Server) {
	*out = *in
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	in.Authentication.DeepCopyInto(&out.Authentication)
	if in.AdminServer != nil {
		in, out := &in.AdminServer, &out.AdminServer
		*out = new(ClientSpec_Server_AdminServer)
		(*in).DeepCopyInto(*out)
	}
	if in.STUNServer != nil {
		in, out := &in.STUNServer, &out.STUNServer
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec_Server.
func (in *ClientSpec_Server) DeepCopy() *ClientSpec_Server {
	if in == nil {
		return nil
	}
	out := new(ClientSpec_Server)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec_Server_AdminServer) DeepCopyInto(out *ClientSpec_Server_AdminServer) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(ClientSpec_Server_AdminServer_Username)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(ClientSpec_Server_AdminServer_Password)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec_Server_AdminServer.
func (in *ClientSpec_Server_AdminServer) DeepCopy() *ClientSpec_Server_AdminServer {
	if in == nil {
		return nil
	}
	out := new(ClientSpec_Server_AdminServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec_Server_AdminServer_Password) DeepCopyInto(out *ClientSpec_Server_AdminServer_Password) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec_Server_AdminServer_Password.
func (in *ClientSpec_Server_AdminServer_Password) DeepCopy() *ClientSpec_Server_AdminServer_Password {
	if in == nil {
		return nil
	}
	out := new(ClientSpec_Server_AdminServer_Password)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec_Server_AdminServer_Username) DeepCopyInto(out *ClientSpec_Server_AdminServer_Username) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec_Server_AdminServer_Username.
func (in *ClientSpec_Server_AdminServer_Username) DeepCopy() *ClientSpec_Server_AdminServer_Username {
	if in == nil {
		return nil
	}
	out := new(ClientSpec_Server_AdminServer_Username)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec_Server_Authentication) DeepCopyInto(out *ClientSpec_Server_Authentication) {
	*out = *in
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(ClientSpec_Server_Authentication_Token)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec_Server_Authentication.
func (in *ClientSpec_Server_Authentication) DeepCopy() *ClientSpec_Server_Authentication {
	if in == nil {
		return nil
	}
	out := new(ClientSpec_Server_Authentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec_Server_Authentication_Token) DeepCopyInto(out *ClientSpec_Server_Authentication_Token) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec_Server_Authentication_Token.
func (in *ClientSpec_Server_Authentication_Token) DeepCopy() *ClientSpec_Server_Authentication_Token {
	if in == nil {
		return nil
	}
	out := new(ClientSpec_Server_Authentication_Token)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientStatus) DeepCopyInto(out *ClientStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientStatus.
func (in *ClientStatus) DeepCopy() *ClientStatus {
	if in == nil {
		return nil
	}
	out := new(ClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Secret) DeepCopyInto(out *Secret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Secret.
func (in *Secret) DeepCopy() *Secret {
	if in == nil {
		return nil
	}
	out := new(Secret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Upstream) DeepCopyInto(out *Upstream) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Upstream.
func (in *Upstream) DeepCopy() *Upstream {
	if in == nil {
		return nil
	}
	out := new(Upstream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Upstream) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamList) DeepCopyInto(out *UpstreamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Upstream, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamList.
func (in *UpstreamList) DeepCopy() *UpstreamList {
	if in == nil {
		return nil
	}
	out := new(UpstreamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpstreamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec) DeepCopyInto(out *UpstreamSpec) {
	*out = *in
	if in.TCP != nil {
		in, out := &in.TCP, &out.TCP
		*out = new(UpstreamSpec_TCP)
		(*in).DeepCopyInto(*out)
	}
	if in.UDP != nil {
		in, out := &in.UDP, &out.UDP
		*out = new(UpstreamSpec_UDP)
		**out = **in
	}
	if in.STCP != nil {
		in, out := &in.STCP, &out.STCP
		*out = new(UpstreamSpec_STCP)
		(*in).DeepCopyInto(*out)
	}
	if in.XTCP != nil {
		in, out := &in.XTCP, &out.XTCP
		*out = new(UpstreamSpec_XTCP)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec.
func (in *UpstreamSpec) DeepCopy() *UpstreamSpec {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_STCP) DeepCopyInto(out *UpstreamSpec_STCP) {
	*out = *in
	out.SecretKey = in.SecretKey
	if in.ProxyProtocol != nil {
		in, out := &in.ProxyProtocol, &out.ProxyProtocol
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(UpstreamSpec_TCP_HealthCheck)
		**out = **in
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(UpstreamSpec_TCP_Transport)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_STCP.
func (in *UpstreamSpec_STCP) DeepCopy() *UpstreamSpec_STCP {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_STCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_STCP_SecretKey) DeepCopyInto(out *UpstreamSpec_STCP_SecretKey) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_STCP_SecretKey.
func (in *UpstreamSpec_STCP_SecretKey) DeepCopy() *UpstreamSpec_STCP_SecretKey {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_STCP_SecretKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_TCP) DeepCopyInto(out *UpstreamSpec_TCP) {
	*out = *in
	out.Server = in.Server
	if in.ProxyProtocol != nil {
		in, out := &in.ProxyProtocol, &out.ProxyProtocol
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(UpstreamSpec_TCP_HealthCheck)
		**out = **in
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(UpstreamSpec_TCP_Transport)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_TCP.
func (in *UpstreamSpec_TCP) DeepCopy() *UpstreamSpec_TCP {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_TCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_TCP_HealthCheck) DeepCopyInto(out *UpstreamSpec_TCP_HealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_TCP_HealthCheck.
func (in *UpstreamSpec_TCP_HealthCheck) DeepCopy() *UpstreamSpec_TCP_HealthCheck {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_TCP_HealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_TCP_Server) DeepCopyInto(out *UpstreamSpec_TCP_Server) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_TCP_Server.
func (in *UpstreamSpec_TCP_Server) DeepCopy() *UpstreamSpec_TCP_Server {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_TCP_Server)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_TCP_Transport) DeepCopyInto(out *UpstreamSpec_TCP_Transport) {
	*out = *in
	if in.BandwdithLimit != nil {
		in, out := &in.BandwdithLimit, &out.BandwdithLimit
		*out = new(UpstreamSpec_TCP_Transport_BandwdithLimit)
		**out = **in
	}
	if in.ProxyURL != nil {
		in, out := &in.ProxyURL, &out.ProxyURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_TCP_Transport.
func (in *UpstreamSpec_TCP_Transport) DeepCopy() *UpstreamSpec_TCP_Transport {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_TCP_Transport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_TCP_Transport_BandwdithLimit) DeepCopyInto(out *UpstreamSpec_TCP_Transport_BandwdithLimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_TCP_Transport_BandwdithLimit.
func (in *UpstreamSpec_TCP_Transport_BandwdithLimit) DeepCopy() *UpstreamSpec_TCP_Transport_BandwdithLimit {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_TCP_Transport_BandwdithLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_UDP) DeepCopyInto(out *UpstreamSpec_UDP) {
	*out = *in
	out.Server = in.Server
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_UDP.
func (in *UpstreamSpec_UDP) DeepCopy() *UpstreamSpec_UDP {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_UDP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_UDP_Server) DeepCopyInto(out *UpstreamSpec_UDP_Server) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_UDP_Server.
func (in *UpstreamSpec_UDP_Server) DeepCopy() *UpstreamSpec_UDP_Server {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_UDP_Server)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_XTCP) DeepCopyInto(out *UpstreamSpec_XTCP) {
	*out = *in
	out.SecretKey = in.SecretKey
	if in.ProxyProtocol != nil {
		in, out := &in.ProxyProtocol, &out.ProxyProtocol
		*out = new(string)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(UpstreamSpec_TCP_HealthCheck)
		**out = **in
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(UpstreamSpec_TCP_Transport)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_XTCP.
func (in *UpstreamSpec_XTCP) DeepCopy() *UpstreamSpec_XTCP {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_XTCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec_XTCP_SecretKey) DeepCopyInto(out *UpstreamSpec_XTCP_SecretKey) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec_XTCP_SecretKey.
func (in *UpstreamSpec_XTCP_SecretKey) DeepCopy() *UpstreamSpec_XTCP_SecretKey {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec_XTCP_SecretKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamStatus) DeepCopyInto(out *UpstreamStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamStatus.
func (in *UpstreamStatus) DeepCopy() *UpstreamStatus {
	if in == nil {
		return nil
	}
	out := new(UpstreamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Visitor) DeepCopyInto(out *Visitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Visitor.
func (in *Visitor) DeepCopy() *Visitor {
	if in == nil {
		return nil
	}
	out := new(Visitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Visitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisitorList) DeepCopyInto(out *VisitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Visitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisitorList.
func (in *VisitorList) DeepCopy() *VisitorList {
	if in == nil {
		return nil
	}
	out := new(VisitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VisitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisitorSpec) DeepCopyInto(out *VisitorSpec) {
	*out = *in
	if in.STCP != nil {
		in, out := &in.STCP, &out.STCP
		*out = new(VisitorSpec_STCP)
		**out = **in
	}
	if in.XTCP != nil {
		in, out := &in.XTCP, &out.XTCP
		*out = new(VisitorSpec_XTCP)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisitorSpec.
func (in *VisitorSpec) DeepCopy() *VisitorSpec {
	if in == nil {
		return nil
	}
	out := new(VisitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisitorSpec_Fallback) DeepCopyInto(out *VisitorSpec_Fallback) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisitorSpec_Fallback.
func (in *VisitorSpec_Fallback) DeepCopy() *VisitorSpec_Fallback {
	if in == nil {
		return nil
	}
	out := new(VisitorSpec_Fallback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisitorSpec_STCP) DeepCopyInto(out *VisitorSpec_STCP) {
	*out = *in
	out.ServerSecretKey = in.ServerSecretKey
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisitorSpec_STCP.
func (in *VisitorSpec_STCP) DeepCopy() *VisitorSpec_STCP {
	if in == nil {
		return nil
	}
	out := new(VisitorSpec_STCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisitorSpec_STCP_ServerSecretKey) DeepCopyInto(out *VisitorSpec_STCP_ServerSecretKey) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisitorSpec_STCP_ServerSecretKey.
func (in *VisitorSpec_STCP_ServerSecretKey) DeepCopy() *VisitorSpec_STCP_ServerSecretKey {
	if in == nil {
		return nil
	}
	out := new(VisitorSpec_STCP_ServerSecretKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisitorSpec_XTCP) DeepCopyInto(out *VisitorSpec_XTCP) {
	*out = *in
	out.ServerSecretKey = in.ServerSecretKey
	if in.Fallback != nil {
		in, out := &in.Fallback, &out.Fallback
		*out = new(VisitorSpec_Fallback)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisitorSpec_XTCP.
func (in *VisitorSpec_XTCP) DeepCopy() *VisitorSpec_XTCP {
	if in == nil {
		return nil
	}
	out := new(VisitorSpec_XTCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisitorSpec_XTCP_ServerSecretKey) DeepCopyInto(out *VisitorSpec_XTCP_ServerSecretKey) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisitorSpec_XTCP_ServerSecretKey.
func (in *VisitorSpec_XTCP_ServerSecretKey) DeepCopy() *VisitorSpec_XTCP_ServerSecretKey {
	if in == nil {
		return nil
	}
	out := new(VisitorSpec_XTCP_ServerSecretKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisitorStatus) DeepCopyInto(out *VisitorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisitorStatus.
func (in *VisitorStatus) DeepCopy() *VisitorStatus {
	if in == nil {
		return nil
	}
	out := new(VisitorStatus)
	in.DeepCopyInto(out)
	return out
}
