apiVersion: v1
kind: Service
metadata:
  name: webhello
  namespace: default
spec:
  selector:
    app: webhello
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhello
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhello
  template:
    metadata:
      labels:
        app: webhello
    spec:
      containers:
        - name: hello
          image: hashicorp/http-echo:1.0
          args: ["-text=hello-from-cluster", "-listen=:8080"]
          ports:
            - containerPort: 8080
