operator:
  image: "ghcr.io/zufardhiyaulhaq/frp-operator"
  tag: "v0.12.0"
  replica: 1

resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 20Mi

metrics:
  secure: false
  serviceMonitor:
    enabled: false
    interval: 30s
    additionalLabels: {}

loadBalancer:
  # -- Bind `Service type=LoadBalancer` with `loadBalancerClass: frp.zufardhiyaulhaq.com/frp` to `ServerPool` servers
  enabled: true
